apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "openbalena-admin.fullname" . }}-remote
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "openbalena-admin.labels" . | nindent 4 }}
    app.kubernetes.io/component: remote

    {{- with .Values.remote.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.remote.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- with .Values.remote.affinity }}
  affinity:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "openbalena-admin.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: remote

      {{- with .Values.remote.labels }}
      {{- toYaml . | nindent 6 }}
      {{- end }}
  replicas: {{ .Values.remote.replicas }}
  template:
    metadata:
      labels:
        {{- include "openbalena-admin.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: remote

        {{- with .Values.remote.labels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      containers:
      - name: {{ .Chart.Name }}-remote
        image: {{ .Values.remote.image.repository }}:{{ .Values.remote.image.tag }}
        imagePullPolicy: {{ .Values.remote.image.pullPolicy }}
        {{- with .Values.remote.resources }}
        resources:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        ports:
          - name: http
            containerPort: 80
          - name: 10000-tcp
            containerPort: 10000
          - name: 10001-tcp
            containerPort: 10001
          - name: 10002-tcp
            containerPort: 10002
          - name: 10003-tcp
            containerPort: 10003
          - name: 10004-tcp
            containerPort: 10004
          - name: 10005-tcp
            containerPort: 10005
          - name: 10006-tcp
            containerPort: 10006
          - name: 10007-tcp
            containerPort: 10007
          - name: 10008-tcp
            containerPort: 10008
          - name: 10009-tcp
            containerPort: 10009
        securityContext:
          privileged: true
          capabilities:
            add: ["SYS_ADMIN", "SYS_RESOURCE"]
        env:
        - name: BALENARC_BALENA_URL
          value: {{ .Values.global.hostname }}

      {{- with .Values.remote.nodeSelector  }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}