apiVersion: v1
kind: Service
metadata:
  name: {{ include "openbalena-admin.fullname" . }}-ui
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "openbalena-admin.labels" . | nindent 4 }}
    app.kubernetes.io/component: ui

    {{- with .Values.ui.service.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.ui.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  selector:
    {{- include "openbalena-admin.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: ui

    {{- with .Values.ui.service.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  ports:
  - port: 80
    name: http
    protocol: TCP
    targetPort: 443
  {{- with .Values.ui.service.externalIPs }}
  externalIPs:
    {{- toYaml . | nindent 4 }}
  {{- end }}
